In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       184 non-null    datetime64[ns]
 1   Open       184 non-null    float64
 2   High       184 non-null    float64
 3   Low        184 non-null    float64
 4   Close      184 non-null    float64
 5   Adj Close  184 non-null    float64
 6   Volume     184 non-null    int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 10.2 KB

In [12]:
df.head(11)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-29,100.589996,100.690002,98.040001,99.620003,93.514290,142718700
1,2014-10-06,99.949997,102.379997,98.309998,100.730003,94.556244,280258200
2,2014-10-13,101.330002,101.779999,95.180000,97.669998,91.683792,358539800
3,2014-10-20,98.320000,105.489998,98.220001,105.220001,98.771042,358532900
4,2014-10-27,104.849998,108.040001,104.699997,108.000000,101.380676,220230600
5,2014-11-03,108.220001,110.300003,107.720001,109.010002,102.328766,199952900
6,2014-11-10,109.019997,114.190002,108.400002,114.180000,107.646675,205166700
7,2014-11-17,114.269997,117.570000,113.300003,116.470001,109.805626,233414700
8,2014-11-24,116.849998,119.750000,116.620003,118.930000,112.124863,181873900
9,2014-12-01,118.809998,119.250000,111.269997,115.000000,108.419746,266589700
10,2014-12-08,114.099998,114.849998,109.349998,109.730003,103.451294,259868000

In [13]:
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
179,2018-03-05,175.210007,180.000000,174.270004,179.979996,179.979996,139852700
180,2018-03-12,180.289993,183.500000,177.619995,178.020004,178.020004,155417500
181,2018-03-19,177.320007,177.470001,164.940002,164.940002,164.940002,172670700
182,2018-03-26,168.070007,175.149994,165.190002,167.779999,167.779999,157898400
183,2018-03-29,167.804993,171.750000,166.899994,167.779999,167.779999,38398505

In [6]:
df.describe()

,Date,Open,High,Low,Close,Adj Close,Volume
count,184,184.000000,184.000000,184.000000,184.000000,184.000000,1.840000e+02
mean,2016-06-30 11:28:41.739130368,127.040245,129.918098,124.340381,127.352663,123.838032,1.910168e+08
min,2014-09-29 00:00:00,92.389999,93.769997,89.470001,90.519997,87.796822,3.839850e+07
25%,2015-08-15 06:00:00,108.882499,112.362499,106.152502,109.204998,105.301765,1.273706e+08
50%,2016-06-30 12:00:00,118.895000,120.865002,116.870003,119.190002,114.999730,1.744112e+08
75%,2017-05-16 18:00:00,144.935005,147.695000,143.227493,144.704994,143.039467,2.207755e+08
max,2018-03-29 00:00:00,180.289993,183.500000,177.619995,179.979996,179.979996,5.003630e+08
std,NaN,24.314449,24.577906,24.176736,24.356534,25.655569,8.160281e+07

In [7]:
df = df.drop_duplicates()

In [11]:
df['Date'] = pd.to_datetime(df['Date'])

In [14]:
df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64